"""modelo inicial

Revision ID: 4e06f139f6d0
Revises: 
Create Date: 2026-10-01 15:38:36.207178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.tipos


# revision identifiers, used by Alembic.
revision: str = '4e06f139f6d0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('dispositivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=40), nullable=False),
    sa.Column('slots_totales', sa.Integer(), nullable=False),
    sa.Column('slots_reservados', sa.JSON(), nullable=False),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.Column('ultimo_contacto', app.tipos.FechaUTC(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    op.create_table('evento_dispositivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=80), nullable=False),
    sa.Column('device_id', sa.String(length=40), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('respuesta', sa.JSON(), nullable=True),
    sa.Column('recibido_en', app.tipos.FechaUTC(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellido', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('rol', sa.Enum('DOCENTE', 'PRECEPTOR', 'ADMIN', name='rol', native_enum=False, length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=True),
    sa.Column('google_sub', sa.String(length=64), nullable=True),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=False),
    sa.Column('bloqueado_hasta', app.tipos.FechaUTC(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_sub')
    )
    op.create_table('llave',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aula_id', sa.Integer(), nullable=False),
    sa.Column('rfid_uid', sa.String(length=20), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('DISPONIBLE', 'RESERVADA', 'PRESTADA', 'BAJA', name='estadollave', native_enum=False, length=20), nullable=False),
    sa.ForeignKeyConstraint(['aula_id'], ['aula.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rfid_uid')
    )
    op.create_table('reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('llave_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=6), nullable=False),
    sa.Column('creada_en', app.tipos.FechaUTC(), nullable=False),
    sa.Column('expira_en', app.tipos.FechaUTC(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'USADA', 'VENCIDA', 'CANCELADA', name='estadoreserva', native_enum=False, length=20), nullable=False),
    sa.ForeignKeyConstraint(['llave_id'], ['llave.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.create_index('ix_reserva_codigo_pendiente', ['codigo'], unique=True, sqlite_where=sa.text("estado = 'PENDIENTE'"), postgresql_where=sa.text("estado = 'PENDIENTE'"))
        batch_op.create_index('ix_reserva_usuario_pendiente', ['usuario_id'], unique=True, sqlite_where=sa.text("estado = 'PENDIENTE'"), postgresql_where=sa.text("estado = 'PENDIENTE'"))

    op.create_table('prestamo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('llave_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('retirado_en', app.tipos.FechaUTC(), nullable=False),
    sa.Column('devuelto_en', app.tipos.FechaUTC(), nullable=True),
    sa.ForeignKeyConstraint(['llave_id'], ['llave.id'], ),
    sa.ForeignKeyConstraint(['reserva_id'], ['reserva.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prestamo')
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.drop_index('ix_reserva_usuario_pendiente', sqlite_where=sa.text("estado = 'PENDIENTE'"), postgresql_where=sa.text("estado = 'PENDIENTE'"))
        batch_op.drop_index('ix_reserva_codigo_pendiente', sqlite_where=sa.text("estado = 'PENDIENTE'"), postgresql_where=sa.text("estado = 'PENDIENTE'"))

    op.drop_table('reserva')
    op.drop_table('llave')
    op.drop_table('usuario')
    op.drop_table('evento_dispositivo')
    op.drop_table('dispositivo')
    op.drop_table('aula')
    # ### end Alembic commands ###
